name: composer update

on: workflow_dispatch

jobs:
  composer_update_job:
    runs-on: ubuntu-latest
    name: composer update
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: composer update action
        uses: kawax/composer-update-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_NAME: cezarpopa
          GIT_EMAIL: cezarpopa@users.noreply.github.com
          APP_SINGLE_BRANCH: 1
          APP_SINGLE_BRANCH_POSTFIX: -updated
          GIT_COMMIT_PREFIX: '[UPDATE]Compose Dependencies'
